version: '3.7'
services:

  # I N F R A S T R U C T U R E
  polynote:
    container_name: polynote
    image: polynote/polynote:0.3.5-2.12
    command: --config /opt/config/config.yml
    ports:
      - 8192:8192
    volumes:
      - "./config.yml:/opt/config/config.yml"
      - "../notebooks:/opt/notebooks/"
    restart: always
    depends_on:
      - elasticsearch
      - kibana
      - grafana
    external_links:
      - "elasticsearch:elasticsearch.local"

  kibana:
    container_name: kibana
    hostname: "kibana.local"
    image: docker.elastic.co/kibana/kibana-oss:7.6.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    restart: always
    depends_on:
      - elasticsearch
    external_links:
      - "elasticsearch:elasticsearch.local"

  grafana:
    container_name: grafana
    hostname: "grafana.local"
    image: grafana/grafana:6.7.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_SECURITY_ADMIN_USER: root
      GF_SECURITY_ADMIN_PASSWORD: rootpassword
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - elasticsearch
    external_links:
      - "elasticsearch:elasticsearch.local"

  elasticsearch:
    container_name: elasticsearch
    hostname: "elasticsearch.local"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
    restart: always